services:
  py-ml-jupyter:
    container_name: py-ml-jupyter
    build: .
    ports: 
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]